/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2022-06-09 00:25:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>제현쌤 팬카페</title>\r\n");
      out.write("<style>\r\n");
      out.write("@font-face {\r\n");
      out.write("	font-family: font;\r\n");
      out.write("	src: url(\"../fonts/LeferiBaseRegular.ttf\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	font-family: font;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: rgb(0, 0, 0);\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*헤더 - 제목 및 회원가입/로그인 부분*/\r\n");
      out.write("header {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	background-color: rgb(255, 255, 255);\r\n");
      out.write("	z-index: 10000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-wrap {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	width: 70%;\r\n");
      out.write("	height: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-logo {\r\n");
      out.write("	width: 80px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-list .list-item {\r\n");
      out.write("	margin-right: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-list .list-item a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-list, .header-wrap {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*메인 - 카테고리 부분*/\r\n");
      out.write("#category {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	width: 250px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	background-color: #5678bd;\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#category ul {\r\n");
      out.write("	padding-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#category ul li a {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	padding-left: 2px;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#category ul li a:hover {\r\n");
      out.write("	border-bottom: 2px solid #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#category h3 {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 메인 - 소개 및 게시물 부분*/\r\n");
      out.write("#intro {\r\n");
      out.write("	padding: 3px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#intro h3 {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	border-bottom: 1px solid #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: start;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#post-table {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	border-spacing: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section .notice {\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-title {\r\n");
      out.write("	margin-bottom: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-title h3 {\r\n");
      out.write("	font-size: 28px;\r\n");
      out.write("	color: #333333;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-top: 1px solid #ccc;\r\n");
      out.write("	border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table a {\r\n");
      out.write("	color: #333;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	line-height: 1.4;\r\n");
      out.write("	word-break: break-all;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table a:hover {\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table th {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table .th-num {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table .th-date {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table th, .board-table td {\r\n");
      out.write("	padding: 14px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table tbody td {\r\n");
      out.write("	border-top: 1px solid #d6d6d6;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table tbody th {\r\n");
      out.write("	padding-left: 28px;\r\n");
      out.write("	padding-right: 14px;\r\n");
      out.write("	border-top: 1px solid #d6d6d6;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".board-table tbody th p {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	width: 1100px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container h3 {\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	border-bottom: 1px solid #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 푸터 영역*/\r\n");
      out.write(".footer {\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: 990px;\r\n");
      out.write("	margin: 60px 282px 0;\r\n");
      out.write("	padding: 24px 90px 24px 0;\r\n");
      out.write("	border-top: 2px solid #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	background-color: #5678bd;\r\n");
      out.write("	margin-top: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-wrap {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-wrap p {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"header\">\r\n");
      out.write("		<div class=\"header-wrap\">\r\n");
      out.write("			<a href=\"./index.html\"><img class=\"header-logo\"\r\n");
      out.write("				src=\"../img/titlePic.jpg\" alt=\"헤더 로고\"></a>\r\n");
      out.write("			<ul class=\"header-list\">\r\n");
      out.write("				<li class=\"list-item\"><a href=\"#\">회원가입</a></li>\r\n");
      out.write("				<li class=\"list-item\"><a href=\"#\">로그인</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<div id=\"main\">\r\n");
      out.write("			<div id=\"category\">\r\n");
      out.write("				<h3>카테고리</h3>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\">카테고리1</a></li>\r\n");
      out.write("					<li><a href=\"#\">카테고리2</a></li>\r\n");
      out.write("					<li><a href=\"#\">카테고리3</a></li>\r\n");
      out.write("					<li><a href=\"#\">카테고리4</a></li>\r\n");
      out.write("					<li><a href=\"#\">카테고리5</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"notice\">\r\n");
      out.write("				<div class=\"page-title\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<h3>제현쌤을 사랑하는 학생들이 모이는 곳</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"board-list\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<table class=\"board-table\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\" class=\"th-num\">번호</th>\r\n");
      out.write("									<th scope=\"col\" class=\"th-title\">제목</th>\r\n");
      out.write("									<th scope=\"col\" class=\"th-date\">등록일</th>\r\n");
      out.write("									<th scope=\"col\" class=\"th-heart\">좋아요</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>1</td>\r\n");
      out.write("									<th><a href=\"#!\">안녕</a></th>\r\n");
      out.write("									<td>2022.06.04</td>\r\n");
      out.write("									<td>1</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>2</td>\r\n");
      out.write("									<th><a href=\"#!\">안녕!!</a></th>\r\n");
      out.write("									<td>2022.06.05</td>\r\n");
      out.write("									<td>1</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>3</td>\r\n");
      out.write("									<th><a href=\"#!\">안녕하세요!</a></th>\r\n");
      out.write("									<td>2012.06.05</td>\r\n");
      out.write("									<td>1</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div id=\"footer\">\r\n");
      out.write("			<div class=\"footer-wrap\">\r\n");
      out.write("				<p>2022 &#8211; 눈물광광조 &#8211;</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
